const login = await fetch('http://127.0.0.1:3001/api/session'); 
const base = 'http://127.0.0.1:5173/api';
const r1 = await fetch(`${base}/session`); const cookie0 = r1.headers.get('set-cookie');
const s0 = await r1.json();
const r2 = await fetch(`${base}/auth/demo`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'http://127.0.0.1:5173', ...(s0.csrf ? { 'X-CSRF-Token': s0.csrf } : {}) }, body: JSON.stringify({ role: 'software' }) });
const cookie = r2.headers.get('set-cookie')?.split(';')[0];
const w = await (await fetch(`${base}/workspace`, { headers: { cookie } })).json();
const andrea = w.students.find(s => s.name === 'Andrea Martínez');
const a = w.assignments.filter(x => x.studentId === andrea.id).map(x => ({ title: x.title, status: x.status, updatedAt: x.updatedAt }));
console.log('Actividades de Andrea:', JSON.stringify(a, null, 1));
const today = new Date().toISOString().slice(0, 10);
console.log('Movimientos de hoy:', JSON.stringify(w.audit.filter(e => e.createdAt.slice(0, 10) === today).map(e => ({ who: e.actorName, action: e.action, at: e.createdAt, detail: e.detail.slice(0, 90) })), null, 1));
const act = w.assignments.find(x => x.studentId === andrea.id && x.title === 'Diseño del panel de seguimiento');
const ev = w.evaluations.filter(e => e.assignmentId === act.id).map(e => ({ at: e.createdAt, current: e.current, feedback: e.feedback, scores: e.scores.map(s => `${w.skills.find(k => k.id === s.skillId)?.name}=${s.score}${s.comment ? ' (' + s.comment + ')' : ''}`) }));
console.log('Evaluaciones de esa actividad:', JSON.stringify(ev, null, 1));
const revs = w.reviews.filter(r => r.assignmentId === act.id).map(r => ({ id: r.id, startsAt: r.startsAt, status: r.status, outcome: r.outcome, version: r.version }));
const dels = w.deliveries.filter(d => d.assignmentId === act.id).map(d => ({ completeness: d.completeness, recordedAt: d.recordedAt }));
console.log('Revisiones de esa actividad:', JSON.stringify(revs, null, 1));
console.log('Entregas:', JSON.stringify(dels), '| versión actual de la actividad:', act.version, '| impedimento:', JSON.stringify(act.blockedReason));
